bns-core/Cargo.toml, bns-core/src/encoder.rs, bns-core/src/signing.rs, bns-core/src/transports/default.rs, bns-core/src/types/ice_transport.rs, src/discoveries/http.rs
=> use b58m instead of hex(b64)

bns-core/Cargo.toml, bns-core/src/channels/default.rs, bns-core/src/channels/wasm.rs, bns-core/src/dht/chord.rs, bns-core/src/dht/did.rs, bns-core/src/ecc.rs, bns-core/src/err.rs, bns-core/src/lib.rs, bns-core/src/message/encoder.rs, bns-core/src/message/handler/mod.rs, bns-core/src/message/mod.rs, bns-core/src/message/payload.rs, bns-core/src/swarm.rs, bns-core/src/transports/default/transport.rs, bns-core/src/transports/helper.rs, bns-core/src/transports/wasm/helper.rs, bns-core/src/transports/wasm/transport.rs, bns-core/src/types/channel.rs, bns-core/src/types/ice_transport/ice_server.rs, bns-core/src/types/ice_transport/mod.rs, bns-core/tests/wasm/test_wasm_transport.rs, src/service/discovery.rs
error refine
1. remove anyhow in bns_core lib, and use thiserror instead
2. bns-node can still use anyhow in application level
=> add bns-core error handle

Cargo.toml, bin/daemon.rs, src/service/is_turn.rs, src/service/mod.rs
=> add bns-is turn server local run as daemon

bns-core/src/message/encoder.rs, bns-core/src/message/handler.rs, src/service/discovery.rs
You can use `encoded_string.into()` for cast String to Encoded.
The string must be value of `encoded.to_string()`;
=> impl From<String> for Encoded

bns-core/src/dht/chord.rs, bns-core/src/dht/stabilization.rs, bns-core/src/err.rs, bns-core/src/message/handler.rs, bns-core/src/message/mod.rs, bns-core/src/swarm.rs, bns-core/src/transports/default/transport.rs, bns-core/tests/default/mod.rs, bns-core/tests/default/test_message_handler.rs, bns-core/tests/mod.rs, bns-core/tests/wasm/test_ice_servers.rs, bns-core/tests/wasm/test_wasm_transport.rs
add test_message_handler_unittes alpha version
=> update test_message_handler unittest

bin/main.rs, src/cli.rs, src/lib.rs
`ring-sim` needs regular outputs for further checking. Otherwise, I have to pattern match stderr and stdout by regex. 😱
=> Feature: export client to ring-sim

bns-core/src/dht/chord.rs, bns-core/src/dht/did.rs, bns-core/src/dht/mod.rs, bns-core/src/dht/peer.rs, bns-core/src/err.rs, bns-core/src/message/handler.rs, bns-core/src/message/mod.rs, bns-core/src/types/ice_transport/mod.rs, bns-core/tests/default/test_message_handler.rs
Suport VirtualNode
related: https://github.com/BNSnet/bns-node/issues/87
=> virtual peer and storage

bin/daemon.rs, bin/main.rs, bns-core/src/swarm.rs, src/cli.rs, src/error.rs, src/service/discovery.rs, src/service/mod.rs, src/service/processor.rs, src/service/request.rs
* add method `listPendings` and `closePendingTransport`
* direct use `session` of swarm
=> add listPendings and closePendingTransport

bns-core/src/dht/chord.rs, bns-core/tests/default/test_message_handler.rs
fix chord find_successor condition
=> fix chord find_successor conditions

bin/main.rs
=> hotfix with session encrypt key

bin/main.rs
Reverts BNSnet/bns-node#118
And Fixed Session
=> Revert "hotfix with session encrypt key"

rings-core/src/message/handlers/mod.rs, rings-core/src/message/types.rs
=> custom handler

Cargo.lock, Cargo.toml, bin/daemon.rs, src/service/is_turn.rs
split turn and rings-node to different thread.
=> modify daemonize

.github/workflows/rings-node.yml, rings-core/src/dht/stabilization.rs, rings-core/src/transports/wasm/transport.rs
modify some log to reduce log output
=> modify info log

.gitignore, Cargo.lock, Makefile, rings-core/.cargo/config.toml, rings-core/Cargo.toml, rings-core/Makefile, rings-core/src/err.rs, rings-core/src/prelude.rs, rings-core/src/storage/mod.rs, rings-core/src/storage/persistence/idb.rs, rings-core/src/storage/persistence/kv.rs, rings-core/src/storage/persistence/mod.rs, rings-core/tests/wasm/mod.rs, rings-core/tests/wasm/test_idb_storage.rs, rings-core/tests/wasm/test_wasm_transport.rs
use IndexedDB as storage for WASM package.
=> Add Persistence storage

rings-core/src/prelude.rs, src/browser/mod.rs, src/jsonrpc/server.rs, src/prelude.rs, src/processor.rs, tests/wasm/processor.rs
* `connect_with_address` will wait for transport channel connected.
* `connect_with_address_without_wait` just create connect, client should
handle channel state.
=> add connect_with_address_without_wait fn

rings-core/src/message/handlers/connection.rs, rings-core/src/message/handlers/mod.rs, rings-core/src/message/types.rs
Reverts RingsNetwork/rings-node#194
Sorry, this pr is not finished.
=> Revert "Test triple nodes connection in all kinds of order"

Cargo.toml, bin/daemon.rs, bin/node.rs
* rename `main.rs` to `node.rs`
* remove `eth_endpoint` option
=> rename main.rs to node.rs

.dockerignore, docker/alpinelinux/Dockerfile
```docker build -t xxxx -f ./docker/alpinelinux/Dockerfile .```
=> add alpinelinux Dockerfile

Cargo.lock, rings-core/Cargo.toml, rings-core/src/message/handlers/connection.rs, rings-core/src/message/handlers/stabilization.rs, rings-core/src/message/handlers/storage.rs, rings-core/src/message/payload.rs
This help user to listen the report msg after send a msg.
=> Let tx_id be same as send msg when report

rings-core/src/dht/chord.rs, rings-core/src/dht/finger.rs, rings-core/src/dht/mod.rs, rings-core/src/dht/successor.rs, rings-core/src/message/handlers/connection.rs, rings-core/src/message/handlers/mod.rs, rings-core/src/message/handlers/stabilization.rs, rings-core/src/message/mod.rs
Close transport inside handler.disconnect. And test it.
Try to fix the https://github.com/RingsNetwork/rings-node/issues/226
=> Close transport inside handler.disconnect

bin/daemon.rs, bin/node.rs, src/util.rs
https://github.com/RingsNetwork/rings-node/issues/252
=> load specific env_file

rings-core/src/ecc/types.rs, rings-core/src/prelude.rs, src/browser/mod.rs, src/prelude.rs
transport_addr should be base58 string of ecc::PublicKey
=> fix transport_addr

.cargo/config.toml, .github/workflows/auto-release.yml, Cargo.toml, src/error.rs, src/jsonrpc/mod.rs, src/jsonrpc/response.rs, src/lib.rs, src/prelude.rs, src/processor.rs, src/seed.rs
if you want to edit feature == browser, you can just set default = "browser" in Cargo.toml.
how to build ring binary
run
```cargo build-node```
=> add feature node and set it to default

bin/rings.rs, rings-core/src/err.rs, rings-core/src/message/handlers/mod.rs, rings-core/src/message/mod.rs, rings-core/src/prelude.rs, rings-core/src/swarm.rs, rings-core/src/tests/default/mod.rs, rings-core/src/tests/default/test_message_handler.rs, rings-core/src/tests/default/test_stabilize.rs, rings-core/src/tests/wasm/mod.rs, src/browser/mod.rs, src/processor.rs, tests/wasm/processor.rs
* Add validator on message handler.
* Remove lock wrapper and mut func of callback and validator. Just pass them in when create message handler.
=> Add validator for message handler

bin/rings.rs, rings-core/src/message/handlers/connection.rs, rings-core/src/message/handlers/mod.rs, rings-core/src/message/handlers/service.rs, rings-core/src/message/handlers/stabilization.rs, rings-core/src/message/handlers/storage.rs, rings-core/src/message/handlers/subring.rs, rings-core/src/swarm.rs, rings-core/src/tests/default/test_message_handler.rs, src/browser/mod.rs, src/processor.rs, src/service/mod.rs, tests/wasm/processor.rs
MessageHandler should be a pure Actor. Use it only when you want to listen to messages.
If you need to do operations with the core, just call functions of swarm.
=> Integrate interfaces to swarm

rings-core/src/chunk.rs, rings-core/src/message/payload.rs, rings-core/src/transports/default/transport.rs, rings-core/src/transports/wasm/transport.rs, src/backend/mod.rs, src/browser/client.rs, src/consts.rs, src/lib.rs
* Remove expired chunks when handle new chunk in chunk list.
* Remove not using MTU in single chunk.
* Enable chunk in wasm transport.
=> Chunk mod enhancement

rings-core/src/dht/chord.rs, rings-core/src/dht/did.rs, rings-core/src/dht/finger.rs, rings-core/src/dht/successor.rs, rings-core/src/dht/types.rs, rings-core/src/message/handlers/connection.rs, rings-core/src/message/handlers/mod.rs, rings-core/src/message/handlers/stabilization.rs, rings-core/src/tests/default/test_message_handler.rs
* Add comments for `test_chord_finger`.
* Change logic in `PeerRing::join`, should add successor if not `is_full` rather than `is_empty`.
* Change the returning `FindSuccessort` to `FindSuccessorForConnect` in `PeerRing::join` for difference with `PeerRing::find_successor`.
* Some other parameter enhancements for methods.
=> Code enhancement

src/browser/client.rs, tests/wasm/browser.rs
=> remove some `wasm_bindgen` extern block.

Cargo.lock, core/src/inspect.rs, core/src/lib.rs, core/src/swarm.rs, core/src/utils.rs, node/Cargo.toml, node/bin/rings.rs, node/src/browser/client.rs, node/src/cli.rs, node/src/jsonrpc/server.rs, node/src/processor.rs, node/src/util.rs
=> Add inspect api

node/src/backend/service/http_server.rs, node/src/error.rs
remove `unwrap()` in backend.http_server
=> handle error in backend

Makefile, core/src/dht/chord.rs, core/src/dht/successor.rs, core/src/dht/types.rs, core/src/message/handlers/connection.rs, core/src/message/payload.rs, core/src/message/protocols/verify.rs, core/src/tests/default/mod.rs, core/src/tests/default/test_stabilization.rs, core/src/tests/mod.rs
FACT
Related Issue: https://github.com/RingsNetwork/rings-node/issues/388
=> CorrectChord: New stabilization algorithm for Correctness

node/src/browser/client.rs, node/src/tests/wasm/browser.rs
1. add `browser::get_address`
2. move `browser::UnsignedInfo::get_address_from_hex_pubkey` to `browser::get_address_from_hex_pubkey`
=> fix `browser::get_address_from_hex_pubkey`

core/Cargo.toml, core/src/consts.rs, core/src/dht/chord.rs, core/src/dht/mod.rs, core/src/dht/types.rs, core/src/message/handlers/connection.rs, core/src/message/handlers/stabilization.rs, core/src/message/handlers/storage.rs, core/src/message/handlers/subring.rs, core/src/message/mod.rs, core/src/prelude.rs, node/src/consts.rs, node/src/prelude.rs, node/src/processor.rs
Changes made:
1) Removed redundant feature flag from the code.
2) Moved the redundant functionality from the message handler to the DHT module for better organization.
3) Added support for node configuration of redundancy.
=> RM redundant feature flag, make redundant configurable by node.

.github/workflows/qaci.yml, .gitignore, Makefile, core/src/swarm.rs, node/src/jsonrpc/server.rs, package.json
From now, node apps can add deps of rings as 
```
"@ringsnetwork/rings-node": "https://github.com/RingsNetwork/rings-node.git#1c7065754d045813dec6e02b3452b4b9ca471246",
```
=> package.json for rings-node

.github/ISSUE_TEMPLATE/bug-report---.md, .github/ISSUE_TEMPLATE/feature-request---.md, .github/ISSUE_TEMPLATE/question--.md
Add ISSUE_TEMPLATE for this project.
User used to open a blank issue when creating.
They choose and fill an issue template now.
No.
Closes #issue
=> docs: add ISSUE_TEMPLATE

.github/workflows/auto-release.yml, package.json
feature
For now, auto release is only for native.
1) Added auto release action for `wasm-unknown-unknown`
2) bump version in package.json to 0.2.6
NIL
NIL
Closes #issue
=> feat: auto release for browser env

.github/workflows/auto-release.yml, .github/workflows/qaci.yml, Makefile, package.json
* Fix wasm auto release config.
* Upgrade rust-cache action.
There are errors and warnings in action logs.
Now cleared by the fixes above.
No.
Closes #issue
=> chore: fix wasm auto release and upgrade rust-cache in CI

core/src/session.rs
chore
feat: rename unsigned session to unsigned proof
Closes #issue
=> chore: rename unsigned session to unsigned proof

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/session.rs, derive/Cargo.toml, node/Cargo.toml, rpc/Cargo.toml
=> chore: bump version to 0.2.7

Cargo.lock, core/src/swarm/mod.rs, core/src/tests/mod.rs, node/Cargo.toml, node/bin/rings.rs, node/src/browser/client.rs, node/src/error.rs, node/src/jsonrpc/handler.rs, node/src/jsonrpc/server.rs, node/src/native/cli.rs, node/src/native/config.rs, node/src/prelude.rs, node/src/processor.rs, rpc/src/client.rs, rpc/src/method.rs, rpc/src/response.rs, transport/src/connections/native_webrtc/mod.rs, transport/src/core/transport.rs
This PR fixes the static checks and tests of rings-node that broken by https://github.com/RingsNetwork/rings-node/pull/466 
Closes #issue
=> chore: upgrade rings-node to use new rings-core

Cargo.lock, core/src/swarm/callback.rs, core/src/swarm/mod.rs, transport/Cargo.toml, transport/src/callback.rs, transport/src/connections/dummy/mod.rs, transport/src/connections/native_webrtc/mod.rs, transport/src/core/callback.rs, transport/src/core/transport.rs
This PR implemented DummyConnection.
Closes #issue
=> feature: implement DummyConnection

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/swarm/callback.rs, core/src/swarm/impls.rs, core/src/swarm/mod.rs, core/src/swarm/types.rs, core/src/tests/wasm/test_ice_servers.rs, core/src/tests/wasm/test_utils.rs, core/src/tests/wasm/test_wasm_transport.rs, node/Cargo.toml, node/src/browser/client.rs, node/src/browser/jsonrpc_client.rs, node/src/browser/mod.rs, node/src/browser/utils.rs, node/src/prelude.rs, node/src/tests/wasm/browser.rs, node/src/tests/wasm/processor.rs, rpc/README.md, transport/Cargo.toml, transport/src/callback.rs, transport/src/connections/dummy/mod.rs, transport/src/connections/native_webrtc/mod.rs, transport/src/connections/web_sys_webrtc/mod.rs, transport/src/core/callback.rs, transport/src/core/transport.rs, transport/src/error.rs, transport/src/lib.rs, transport/src/notifier.rs
=> feature: implement WebSysWebrtcConnection

core/src/dht/stabilization.rs, core/src/inspect.rs, core/src/message/handlers/connection.rs, core/src/swarm/impls.rs, core/src/swarm/mod.rs, core/src/swarm/types.rs, core/src/tests/default/test_message_handler.rs, core/src/tests/mod.rs, core/src/tests/wasm/test_wasm_transport.rs, core/src/types/mod.rs, node/src/browser/client.rs, node/src/lib.rs, node/src/prelude.rs, node/src/processor.rs, node/src/tests/wasm/processor.rs, transport/README.md, transport/src/connection_ref.rs, transport/src/connections/dummy/mod.rs, transport/src/connections/mod.rs, transport/src/connections/native_webrtc/mod.rs, transport/src/connections/web_sys_webrtc/mod.rs, transport/src/core/callback.rs, transport/src/core/mod.rs, transport/src/core/transport.rs, transport/src/error.rs, transport/src/ice_server.rs, transport/src/lib.rs
=> Add ConnectionRef and update docs

core/src/swarm/impls.rs
=> Reset not connected connection when handshaking

core/src/message/handlers/connection.rs
=> fix: fix tests that changed by DummyTransport

Cargo.lock, core/Cargo.toml, core/src/ecc/mod.rs, core/src/ecc/signers/mod.rs, core/src/ecc/signers/secp256r1.rs, core/src/ecc/types.rs, core/src/error.rs, core/src/session.rs
feature
Added supporting for secp256r1 on ECDSA
ref: https://eips.ethereum.org/EIPS/eip-7212
Closes #issue
=> feat: add support for curve secp256r1 (NistP256)

Cargo.toml, README.md, core/Cargo.toml, derive/Cargo.toml, node/Cargo.toml, rpc/Cargo.toml, transport/Cargo.toml
=> chore: bump version to 0.3.1

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/swarm/impls.rs, derive/Cargo.toml, node/Cargo.toml, rpc/Cargo.toml, transport/Cargo.toml, transport/src/connections/dummy/mod.rs, transport/src/connections/native_webrtc/mod.rs
Fix sdp issue, the sdp types in wasm and native are not consistent
1. Set WASM SDP type to String
2. Set Dummy SDP type to String
3. Bump version to 0.3.2
Closes #issue
=> bugfix: Set SDP type to String

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/message/handlers/storage.rs, derive/Cargo.toml, node/Cargo.toml, rpc/Cargo.toml, transport/Cargo.toml
- [] Tests for the changes have been added (for bug fixes/features)
- [] Docs have been added / updated (for bug fixes / features)
Bug fix:
Fix unhandled DHT Event:
```
2023-11-10T10:46:57.127375Z ERROR rings_core::swarm: Message handler failed on handling event: PeerRingUnexpectedAction(
MultiActions(
[
RemoteAction(
Did(
0x11e807fcc88dd319270493fb2e822e388fe36ab0,
),
FindVNode(
Did(
0xc19c8090b355f892290e23e66af3a2988a6185ed,
),
),
),
],
),
)
```
Closes #issue
=> bugfix: handle storage search action

Cargo.toml, core/src/dht/stabilization.rs
timeout on wasm case is not actually works, and it was fixed 2.5sec
use self.timeout
Closes #issue
=> bugfix: fixed timeout in wasm stabilazation

Cargo.lock, core/Cargo.toml, core/src/dht/stabilization.rs
=> chore: experimental feature should contains std

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/dht/stabilization.rs
=> bugfix: stab timeout should be 1000 times secs instead of div 

.github/workflows/qaci.yml, core/src/ecc/signers/secp256r1.rs, core/src/lib.rs, core/src/message/mod.rs, core/src/message/protocols/verify.rs, core/src/message/types.rs, core/src/session.rs, core/src/swarm/callback.rs, core/src/swarm/types.rs, transport/src/connection_ref.rs, transport/src/connections/mod.rs, transport/src/core/callback.rs, transport/src/core/mod.rs, transport/src/core/transport.rs, transport/src/ice_server.rs, transport/src/pool.rs
=> docs: update docs and add ci for docs

README.md, core/README.md, node/README.md, transport/README.md
=> chore: update readme

README.md, core/src/ecc/signers/bip137.rs, examples/ffi/rings.py, node/src/backend/ffi.rs, node/src/backend/mod.rs, node/src/provider/ffi.rs
- [x ] Tests for the changes have been added (for bug fixes/features)
- [ x] Docs have been added / updated (for bug fixes / features)
Closes #issue
=> feat: support FFI backend

examples/ffi/rings.py, node/src/jsonrpc/handler.rs, node/src/provider/ffi.rs, node/src/provider/mod.rs
=> bugfix: sig should be 65 bytes

Cargo.lock, Cargo.toml, examples/ffi/rings.h, examples/ffi/rings.py, node/src/provider/ffi.rs, package.json
bugfix
1. async listen needs tokio runtime
added runtime to listen, rm async_listen, for now ffi::listen is default as async
Closes #issue
=> bugfix: add runtime to ffi::listen

package.json
Fix the npm pack procedure that is invoked in the auto-release CI.
Closes #issue
=> ci: fix npm pack

.github/workflows/auto-release.yml
=> chore: add g++

.github/workflows/auto-release.yml
=> Chore modify git action

.github/workflows/auto-release.yml
=> chore: fixed matrix

Cargo.lock, Cargo.toml, package.json
=> Bump version

.github/workflows/qaci.yml, Cargo.lock, crates/core/src/swarm/impls.rs, examples/native/Cargo.toml, examples/native/src/main.rs
Add basic connecting and message sending example in native provider example.
Closes #issue
=> chore: update native example

crates/transport/Cargo.toml, crates/transport/src/callback.rs, crates/transport/src/connections/native_webrtc/mod.rs, crates/transport/src/connections/web_sys_webrtc/mod.rs, crates/transport/src/error.rs, crates/transport/src/notifier.rs, examples/native/src/main.rs
=> feature: set timeout when wait for datachannel open

Cargo.toml, index.ts, package.json
=> fix: import path of index.ts

crates/node/src/tests/wasm/browser.rs
=> test: sdd test_send_backend_message

crates/node/src/tests/wasm/snark.rs, crates/snark/src/tests/native/test_witness.rs, crates/snark/src/tests/wasm/test_wasm_witness.rs
=> fix: fix remote witness path

Cargo.lock, crates/core/Cargo.toml, crates/core/src/dht/chord.rs, crates/core/src/dht/types.rs, crates/core/src/message/handlers/mod.rs, crates/core/src/message/handlers/stabilization.rs, crates/core/src/message/types.rs, crates/core/src/swarm/mod.rs, crates/core/src/tests/default/test_stabilization.rs
=> fix: stabilization predecessor notify logic

.github/workflows/auto-release.yml
=> Incr release build timeout

.github/workflows/auto-release.yml, crates/core/src/dht/did.rs
=> ci: incr timeout for release, fix a typo

.github/workflows/issue.yml
=> chore: notify new issue to developers

crates/core/src/error.rs, crates/core/src/message/handlers/connection.rs, crates/core/src/message/handlers/mod.rs, crates/core/src/message/payload.rs, crates/core/src/swarm/impls.rs, crates/core/src/swarm/mod.rs, crates/core/src/tests/default/mod.rs, crates/core/src/tests/default/test_connection.rs, crates/core/src/tests/default/test_stabilization.rs, crates/transport/src/connections/dummy/mod.rs
=> feat: try to resolve conflicts during handshake

Cargo.lock, Cargo.toml, crates/core/src/tests/default/test_stabilization.rs, package.json
=> fix: case error in js proto and bump version

crates/core/src/swarm/impls.rs, crates/core/src/tests/default/test_connection.rs, crates/core/src/tests/default/test_stabilization.rs, crates/transport/src/connections/dummy/mod.rs
This PR fix the dummy transport to pass `test_handshake_on_both_sides` and `test_handshake_on_both_sides`.
Closes #issue
=> fix: dummy transport

README.md, crates/node/src/backend/snark/browser.rs, crates/node/src/backend/snark/mod.rs, crates/snark/README.md, package.json
=> fix: use forked protobufjs

crates/node/src/backend/snark/browser.rs
=> fix: export split

Cargo.lock, Cargo.toml
=> chore: update webrtc

Cargo.lock, crates/transport/src/notifier.rs
1. fixed transport feature flag
2. update cargo.lock
=> chore: fixed transport feature flag, and update cargo.lock

Cargo.lock, crates/snark/Cargo.toml
=> chore: update nova

Cargo.lock, crates/node/src/backend/snark/browser.rs, crates/node/src/backend/snark/mod.rs, crates/node/src/backend/types/snark.rs, crates/snark/Cargo.toml, crates/snark/src/snark/mod.rs, crates/snark/src/tests/native/test_snark.rs, examples/snark/bn256.rs, examples/snark/merkle_tree.rs
=> chore: update nova-snark to official 0.35

crates/snark/Cargo.toml
=> chore: fix nova-snark, only use holo asm on arch x86_64

crates/snark/Cargo.toml
=> chore: rings-snark: use portable nova as default

crates/snark/Cargo.toml
=> chore: fixed plonk config code style

.github/workflows/auto-release.yml, cliff.toml
This PR corrects the repo address in cliff, and also fixes the title of prerelease.
Closes #issue
=> ci: fix repo address in cliff

crates/core/src/message/handlers/connection.rs, crates/core/src/message/handlers/stabilization.rs, crates/core/src/message/handlers/storage.rs, crates/core/src/tests/default/mod.rs, crates/core/src/tests/default/test_connection.rs
This PR attempts to stabilize the test by removing unnecessary intermediate state checks in stabilization test.
No breaking change.
Closes #issue
=> ci: relax intermediate state check in stabilization test

.github/workflows/qaci.yml, crates/core/src/message/handlers/connection.rs, crates/core/src/swarm/transport.rs, crates/core/src/tests/default/mod.rs, crates/transport/src/connections/dummy/mod.rs
This PR use channel instead of local call to fix the inconsistent behavior of dummy transport.
Closes #issue
=> ci: fix dummy transport and add dummy test back

index.ts, package.json, tsconfig.json
Reverts RingsNetwork/rings#574
Reverts because on testcase, it failed on load RPC components from rings_node_pb
=> Revert "chore: fix tsconfig and pbjs issue"

Cargo.lock, Cargo.toml, package.json
=> chore turn off wasm opt

Cargo.toml
=> Chore disable opt
