rustfmt.toml
Force set rustfmt rule.
More options you can view at https://rust-lang.github.io/rustfmt/
=> add rustfmt config file

bin/daemon.rs, bin/main.rs, bns-core/src/message/handler.rs, bns-core/src/types/message.rs
```
#[cfg_attr(feature = "wasm", async_trait(?Send))]
#[cfg_attr(not(feature = "wasm"), async_trait)]
pub trait MessageListener {
async fn listen(self: Arc<Self>);
}
```
instead of
```
#[cfg_attr(feature = "wasm", async_trait(?Send))]
#[cfg_attr(not(feature = "wasm"), async_trait)]
pub trait MessageListener {
async fn listen(self);
}
```
=> use Arc<self> instead self

bin/main.rs, bns-core/src/dht/chord.rs, bns-core/src/dht/stabilization.rs, bns-core/src/message/handler.rs, bns-core/src/swarm.rs, bns-core/src/transports/default/transport.rs, bns-core/tests/default/mod.rs, bns-core/tests/default/test_message_handler.rs, bns-core/tests/default/test_stabilize.rs, bns-core/tests/wasm/test_message_handler.rs
1. refine unittest, remove `listen_once` and use futures::join as background programs
2. `handle_join` should consider two situation, first of all is `fingers` is empty, juse join local and set successor, others need send remote message find successor
3. parse ice_server as a stun list
=> update stabilize test and ice_server list

rings-core/src/dht/stabilization.rs, rings-core/src/err.rs, rings-core/src/message/handlers/connection.rs, rings-core/src/message/handlers/mod.rs, rings-core/src/message/handlers/storage.rs, rings-core/src/message/payload.rs, rings-core/src/message/protocol.rs, rings-core/src/swarm.rs, rings-core/src/transports/default/transport.rs, rings-core/src/transports/wasm/transport.rs, rings-core/tests/default/test_message_handler.rs, rings-core/tests/wasm/test_wasm_transport.rs, src/browser/mod.rs, src/jsonrpc/server.rs, src/processor.rs
The new relay fields:
```rust
{
// A push only stack. Record routes when sending message.
path: Vec<Did>,
// Move this cursor to flag the top of stack when reporting.
path_end_cursor: usize,
// The next node to handle the message. Current handler will pick transport by this field.
// When and only when located at the end of the message propagation, the next_hop is none.
next_hop: Some<Did>,
// The final destination of the message. May be customized when sending. Cannot change when reporting.
// It may help handler to find out next_hop in some situations.
destination: Did,
}
```
To **send** a message, you must provide both next_hop and destination.
```rust
pub async fn send_message(
&self,
next_hop: &Did,
destination: &Did,
msg: Message,
) -> Result<()> {...}
```
To **send** or **report** …
=> new structure of relay

bin/daemon.rs, rings-core/src/dht/stabilization.rs, rings-core/src/dht/vnode.rs, rings-core/src/lib.rs, rings-core/src/message/handlers/connection.rs, rings-core/src/message/handlers/mod.rs, rings-core/src/message/handlers/storage.rs, rings-core/src/message/mod.rs, rings-core/src/message/payload.rs, rings-core/src/message/protocols/mod.rs, rings-core/src/message/protocols/relay.rs, rings-core/src/message/protocols/verify.rs, rings-core/src/message/types.rs, rings-core/src/session.rs, rings-core/src/swarm.rs, rings-core/src/transports/default/transport.rs, rings-core/src/transports/wasm/transport.rs, rings-core/tests/default/test_message_handler.rs, src/browser/mod.rs, src/error.rs, src/processor.rs
- Rename `MessageRelay` to `MessagePayload`. 
- `MessageRelay` is now an independent struct for handling relay protocol in `message.protocols` module.
- Split verification and relay fields of `MessagePayload` to `message.protocols` module.
- Add some construct functions on `MessagePayload` and `MessageRelay`.
- Add two traits `PayloadSender` and `HandleMsg`.
- Implement those two traits for `MessageHandler`.
=> Split protocols, add two traits PayloadSender and HandleMsg

src/browser/mod.rs, src/lib.rs, src/service/mod.rs, src/util.rs
```typescript
import { internal_info } from 'rings-node'
const info = internal_info()
console.log(`build_version: ${info.build_version}`)
```
=> add build_version for browser

node/bin/rings.rs, node/src/jsonrpc/server.rs
Handshake info should be encoded with base58, To make it easier for manual creation and copying/pasting of handshake information
=> handshake info should be encoded

node/src/backend/extension.rs, node/src/backend/service/http_server.rs, node/src/config/mod.rs
For now, you can ignore the below field in `config.yaml`:
* backend: default value: []
* extension: default value: Path []
=> Make config file forward compat

Cargo.toml, core/Cargo.toml, derive/Cargo.toml, node/Cargo.toml, rpc/Cargo.toml
Release 0.2.6 (node, core)
Related PRs, only showing breaking change and new features.
```
refactor!: Initialize SessionManager with builder pattern (#436)
feat!: Support loading wasm/wat as background extension (#432)
feat!: Encode handshake info (#430)
refactor!: Split swarm from message handler using events (#420)
refactor!: Add rings-rpc module (#409)
feat!: Set data to be redundant (#419)
feat!: Add bip137, and support verification with bitcoin (#411)
feat: Inspect storage (#389)
refactor!: Use global `this` for browser environment (#382)
feat: Add inspect API (#368, #369, #389)
```
=> release: 0.2.6

core/Cargo.toml, core/src/transports/default/transport.rs, core/src/transports/dummy/transport.rs, core/src/transports/wasm/transport.rs, core/src/types/ice_transport/mod.rs, node/src/tests/wasm/processor.rs
I found that this API provides information similar to `chrome://webrtc-internals` when attempting to resolve issue #445.
It is particularly helpful when you are not working within the Chrome UI.
This PR export `get_stats` method of `RtcPeerConnection` to `Transport`, allowing for easy data manipulation through json serialization.
Cannot inspect transport stats. Can only get its connection state.
Can get stats by invoke `get_sats` method of `Transport`.
No breaking change.
The docs of RTCPeerConnection.get_stats method: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats
Closes #issue
=> feature: get transport connection stats

core/src/message/handlers/connection.rs, core/src/message/handlers/dht.rs, core/src/message/handlers/storage.rs, core/src/swarm/mod.rs, core/src/transports/default/transport.rs
Bug fix
When handling the FixFingerTable event, JoinDHT was triggered without checking the connection. This may lead to incorrect DHT status.
The VNodeOperation handler did not handle MultiEvent.
1. Trigger connect before JoinDHT.
2. Support MultiEvent on VNodeOperation handler
No
Closes #issue
=> bugfix: fix successor updater and vnode_op

Cargo.lock, core/Cargo.toml, core/src/dht/finger.rs, core/src/dht/stabilization.rs, core/src/error.rs, core/src/lib.rs, core/src/measure.rs, core/src/storage/persistence/kv.rs, core/src/swarm/impls.rs, core/src/swarm/mod.rs, core/src/swarm/types.rs, core/src/transports/default/transport.rs, core/src/transports/manager.rs, core/src/transports/wasm/transport.rs, derive/Cargo.toml, derive/src/derives.rs, derive/src/lib.rs, node/src/consts.rs, node/src/measure.rs
feature
related issue https://github.com/RingsNetwork/rings-node/issues/399
In the current scenario, the DHT may attempt to establish a connection to did_a, but this can fail due to incorrect configuration or network issues. The existing implementation might repeatedly try to establish the connection, potentially causing the system's file descriptor limit to be reached very quickly.
1. A judgement for node behaviour, make sure node is behaviour `good`.
2. A measurement of node behavior, ensuring that the difference between disconnect and connect counts exceeds the THRESHOLD.
3. Throw a new error type: NodeBehaviourBad.
4. Record behaviour on function `connect`, `connect_via` and `disconnect`.
No
After this modify, if a node is behaviour no good, it will printout errors.
Closes #issue
=> feat: limit connection by measurement

node/src/browser/client.rs, node/src/error.rs, node/src/processor.rs
feature
Three or four steps is needed for creating a client instance, and it's hard to understand for users.
Make browser::client can be contracture with one stop function.
```rust
#[wasm_bindgen(constructor)]
pub fn new_instance(
ice_servers: String,
stabilize_timeout: usize,
account: String,
account_type: String,
// Signer should be `async function (proof: string): Promise<Unit8Array>`
signer: js_sys::Function,
callback: Option<MessageCallbackInstance>,
//) -> Result<Client, error::Error> {
) -> js_sys::Promise 
```
The impl can be used with (this example if from rings_ext_v2):
```typescript
let signer = async (proof: string): Promise<Uint8Array> => {
const { signed } = await sendMessage(
'sign-message',
{
auth: proof,
},
'popup'
)
return new Uint8Array(hexToBytes(signed));
}
let …
```
=> feat!: one stop constructure function for browser::client

Cargo.lock, core/Cargo.toml, core/src/dht/did.rs, core/src/ecc/mod.rs, core/src/ecc/signers/bip137.rs, core/src/ecc/signers/ed25519.rs, core/src/ecc/signers/eip191.rs, core/src/ecc/signers/secp256k1.rs, core/src/prelude.rs, core/src/storage/memory.rs, core/src/tests/wasm/test_idb_storage.rs, node/src/browser/client.rs, node/src/jsonrpc/server.rs, node/src/prelude.rs, node/src/processor.rs, node/src/tests/wasm/browser.rs, node/src/tests/wasm/processor.rs
* Remove web3 package dependency. Use specific ethereum-type and tiny-keccak packages.
* Fix the display format for Did. Now it has a `0x` prefix when display.
The web3 is a huge package. Rings-core crate do not need all the features of it.
It is replaced by the sub-dependencies ethereum-type and tiny-keccak.
No breaking change.
Closes #issue
=> chore: remove web3 dependency and fix Did display prefix

core/src/message/handlers/connection.rs, core/src/types/mod.rs, transport/src/connections/dummy/mod.rs
We forgot to enable DummyTransport in the dummy tests previously. This PR has now enabled it.
Additionally, we also fixed two bugs in DummyTransport:
1. The state changing of closing was incorrect. It should first change to disconnected before becoming closed. And this process should be skipped if the state is already closed.
2. The global hub CBS and CONNS was using cid as a key, which caused conflicts when connecting multiple nodes together since different connections with the same cid could appear on different nodes. We have changed it to use a random number generated by each connection as the key instead.
The DummyTransport is not enabled in dummy tests and there are bugs.
Bug fixed. Enabled.
No breaking change
Closes #issue
=> ci: enable and fix DummyTransport in tests

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/utils.rs, derive/Cargo.toml, node/Cargo.toml, package.json, rpc/Cargo.toml, transport/Cargo.toml
bugfix
Currently the mapper of Rust -> JsValue is not JSON compatible.
Because Map can not be directly serialize in js.
No
Closes #issue
=> bugfix: make JsValue serializer JSON compatible

Cargo.lock, Cargo.toml, core/src/session.rs, node/Cargo.toml, node/bin/rings.rs, node/src/error.rs, node/src/native/config.rs, node/src/util.rs
This PR moves the session_sk dump from the config file to a separate session_sk file. It then uses the path of that file as a replacement.
Additionally, this PR adds a `new-session` subcommand in the rings bin, allowing users to refresh their session_sk or generate a new one.
However, it is important to note that users still need to restart the rings node after updating the session_sk file.
Cannot generate a config file with template engine since the session_sk need rings bin to generate.
Cannot update session_sk without touch config file when its expired.
The `session_sk` config is now a file path. Simply use `rings new-session` to generate it when needed.
No breaking change.
Closes #issue
=> feature: move session_sk to a separate file in config

.github/workflows/qaci.yml, Cargo.lock, Cargo.toml, core/Cargo.toml, examples/ffi/rings.py, examples/native/Cargo.toml, examples/native/src/main.rs, node/Cargo.toml, node/src/backend/browser.rs, node/src/backend/ffi.rs, node/src/backend/mod.rs, node/src/backend/native/extension.rs, node/src/backend/native/mod.rs, node/src/backend/native/service/mod.rs, node/src/backend/types.rs, node/src/processor.rs, node/src/provider/mod.rs, rpc/Cargo.toml, transport/Cargo.toml
This PR add an example of native provider.
Closes #issue
=> feature: add an example of native provider

crates/core/src/measure.rs, crates/core/src/swarm/impls.rs, crates/derive/src/derives.rs, crates/node/src/consts.rs
The method `good` of `ConnectBehaviour` trait raise `attempt to subtract with overflow` panic when `conn < disconn` somehow.
Closes #issue
=> fix: subtract overflow in measure

crates/node/src/logging.rs, crates/transport/src/connections/native_webrtc/mod.rs
This PR disables mdns query to prevent overload when creating repeated connections in lightweight hardware.
Closes #issue
=> feature: disable multicast dns in native webrtc connection

.github/workflows/auto-release.yml, .github/workflows/qaci.yml
The CI always failed with log:
```
API rate limit exceeded for [some ip]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
According to https://github.com/arduino/setup-protoc/issues/6 , this PR should fix that.
https://github.com/arduino/setup-protoc/issues/6
Closes #issue
=> ci: fix protoc setup limitation

index.ts, package.json, tsconfig.json
=> fix: npm package export

crates/node/src/backend/browser.rs, crates/node/src/backend/mod.rs, crates/node/src/backend/snark/browser.rs, crates/node/src/backend/snark/mod.rs, crates/node/src/error.rs, crates/node/src/provider/mod.rs, crates/node/src/tests/wasm/browser.rs, crates/snark/src/snark/mod.rs
=> feat: make browser backend behavior more general

.github/workflows/qaci.yml, Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/node/Cargo.toml, crates/node/src/backend/browser.rs, crates/node/src/error.rs, crates/node/src/util.rs, crates/transport/Cargo.toml, package.json
…fuse.
1) fixed version issue,
2) use default instead minimal for avoid confuse
Closes #issue
=> chore: fix webrtc version, and flag of features

crates/node/src/provider/browser/provider.rs
=> send message with plaintext

crates/core/src/message/handlers/connection.rs, crates/core/src/message/types.rs, crates/core/src/swarm/builder.rs, crates/core/src/swarm/transport.rs, crates/core/src/tests/default/mod.rs, crates/core/src/tests/wasm/mod.rs, crates/node/src/native/config.rs, crates/node/src/processor.rs, crates/node/src/provider/browser/provider.rs, crates/node/src/provider/ffi.rs, crates/node/src/provider/mod.rs, crates/node/src/tests/native/mod.rs, crates/node/src/tests/wasm/mod.rs, examples/ffi/rings.h, examples/ffi/rings.py, examples/native/src/main.rs
This PR introduces a `network_id` field in `ConnectNodeSend` message. It's used to prevent nodes from different networks from connecting to each other.
There is a breaking change in config file.
User must specify network_id in config file now.
Closes #issue
=> feat!: differentiate swarms based on network_id

Cargo.toml, crates/core/src/ecc/signers/bip137.rs, crates/core/src/error.rs, package.json
Fixed: recovery ID of compressed bitcoin signature is not covered in our implementation.
Protocol Details:
| y-parity | x-order       | compression | recovery id | v  |
|----------|---------------|-------------|-------------|----|
| even     | less than n   | false       | 0           | 27 |
| odd      | less than n   | false       | 1           | 28 |
| even     | more than n   | false       | 2           | 29 |
| odd      | more than n   | false       | 3           | 30 |
| even     | less than n   | true        | 0           | 31 |
| odd      | less than n   | true        | 1           | 32 |
| even     | more than n   | true        | 2           | 33 |
| odd      | more than n   | true        | 3           | 34 |
=> bugfix! fix bip137 sig

.github/workflows/qaci.yml, Cargo.lock, crates/core/Cargo.toml, crates/core/src/ecc/elgamal.rs, crates/core/src/ecc/mod.rs, crates/core/src/ecc/signers/bip137.rs, crates/core/src/ecc/signers/bls.rs, crates/core/src/ecc/signers/ed25519.rs, crates/core/src/ecc/signers/eip191.rs, crates/core/src/ecc/signers/mod.rs, crates/core/src/ecc/signers/secp256k1.rs, crates/core/src/ecc/signers/secp256r1.rs, crates/core/src/ecc/types.rs, crates/core/src/error.rs, crates/core/src/session.rs
* Map privatekey to bls primefield
* Map publickey to projective point of G2
* Implemented sign and verify of bls
* implementation of bls aggregate
* The msg is extending with prefix `"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_` which is as same as filecoin's implementation.
=> feat: support BLS (Boneh-Lynn-Shacham) signature
